version: '3'

services:
  flask-app:
    image: zoliao2024/bitcoin-be:v0.0.1
    container_name: bitcoin-be-container
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: bitcoin_explorer
      FLASK_PORT: 5000
    ports:
      - 5000:5000
    networks:
      - bitExp-network

  backend-app:
    image: zoliao2024/bitcoin-ingestion:v0.0.3
    container_name: bitcoin-ingestion-container
    command: [ "--rpc-user", "${RPC_USER}", "--rpc-pwd", "${RPC_PASSWORD}", "--rpc-url", "${RPC_URL}", "--db-user", "${MYSQL_USER}", "--db-pwd", "${MYSQL_PASSWORD}", "--db-host", "${MYSQL_HOST}", "--redis-host", "${REDIS_HOST}", "--redis-port", "${REDIS_PORT}", "--redis-pwd", "${REDIS_PASSWORD}" ]
    networks:
      - bitExp-network

networks:
  bitExp-network:
    external: true
