# This is a basic workflow to help you get started with Actions

name: Deploy on Push to Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Remote Server
        run: |
          sshpass -p "${{ secrets.CLOUD_PWD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.CLOUD_USERNAME }}@${{ secrets.CLOUD_HOST }} << 'EOF'
            cd ~/githubRepo/bitcoin-deploy
            source ~/prod.env
            git checkout main
            git pull --rebase
            docker-compose up -d
          EOF
